### ISSUE TITLE
chap6 서블릿/JSP를 활용해 동적인 웹 애플리케이션 개발하기

### ISSUE THREAD

**Issue by mybloom** [mybloom/Next-Step#4]
## 학습 목표
- 세션 구현으로 세션 동작원리 이해하기
- MVC 패턴 기반 프레임워크 구현으로 MVC 개념 이해하기

## git branch 정보
- 메인 브랜치 : 2-mvc-framework 
- 내 브랜치 : terry-2-mvc-framework
- feature 브랜치 : chap6-xxxx

## Question
- [ ] null check시 if 조건문으로 하지 않고 Optional 로 할 수 있는지? : ListUserServlet
- [ ] User user = (User) session.getAttribute("user") 는 브라우저에서 확인할 수 있는지? 있다면 어떻게 확인할 수 있는지
- [ ] 테스트코드 : 서블릿 refactoring 확인용 test 코드 작성 부분 확인해보기 
- [ ] 테스트코드 : header/footer 처럼 공통 부분 빼고 나서 잘 작동하는지 확인하는 테스트코드는 어떻게? 구지 해야 하는건가?
- [ ] 개인정보 수정 시 , 자신의 정보가 아닐 경우 `같은 페이지로 forward` : 같은 페이지 forword가 `맞는 것인지는 모르겠다.`

## Todo
- [ ] forward, redirect 차이 
- [x] 일반적인 접근이 아닌 경로로 접근하는 방법 알아보기. 예) 해당 사용자로 로그인하지 않고 개인정보 수정 post에 접근하는 방법 
	- postman, 등
	- postman: form으로 post요청 시, body type을 `x-www-form-urlencoded`로 놓고 설정하면 된다.

## 개발시 유의한 것
- 서버로 들어오는 데이터 검증 : 비즈니스 로직이 로그인한 유저라면 form에서 들어온 데이터를 사용할 때, 로그인한 정보와 맞는지 확인. 
- 기존 제공하는 Exception을 확인해서 사용. 
   - RuntimeException을 상속하는 익셉션을 주로 확인.
   - ServletException : cheked Exception. class
